# This is a basic workflow to help you get started with Actions

name: build reindeer-comic for Win/Mac

# Controls when the workflow will run
on:
  release:
    types: [prereleased, released]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    # windows-2019, macos-10.15, ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-10.15]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Fetch Sources
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.release.tag_name }}
          
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        
      - name: npm install
        run: |
          npm install yarn
          
      - name: yarn install
        run: |
          yarn install
          
      - name: build app for win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: matrix.os == 'windows-2019'
        run: |
          yarn run electron:build
          
      - name: build app for mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: matrix.os == 'macos-10.15'
        run: |
          yarn run electron:build
          
          
      - name: cleanup artifacts for windows
        if: matrix.os == 'windows-2019'
        run: |
          mkdir artifacts
          mv release/*.exe artifacts || true
      - name: cleanup artifacts for macosZ
        if: matrix.os == 'macos-10.15'
        run: |
          mkdir artifacts
          mv release/*.dmg artifacts || true
          
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: artifacts
          
          
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./artifacts/**
